services:
  - type: web
    name: colectiva-ahorro-peru
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
    autoDeploy: true
