/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampanasIndexRouteImport } from './routes/campanas.index'
import { Route as CampanasCampaignIdRouteImport } from './routes/campanas.$campaignId'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoProductIdRouteImport } from './routes/catalogo.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasIndexRoute = CampanasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampanasRoute,
} as any)
const CampanasCampaignIdRoute = CampanasCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampanasRoute,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoProductIdRoute = CatalogoProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanas': typeof CampanasRouteWithChildren
  '/catalogo': typeof CatalogoRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/campanas/$campaignId': typeof CampanasCampaignIdRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/campanas/': typeof CampanasIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/campanas/$campaignId': typeof CampanasCampaignIdRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/campanas': typeof CampanasIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanas': typeof CampanasRouteWithChildren
  '/catalogo': typeof CatalogoRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/campanas/$campaignId': typeof CampanasCampaignIdRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/campanas/': typeof CampanasIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campanas'
    | '/catalogo'
    | '/dashboard'
    | '/campanas/$campaignId'
    | '/catalogo/$productId'
    | '/campanas/'
    | '/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/campanas/$campaignId'
    | '/catalogo/$productId'
    | '/campanas'
    | '/catalogo'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campanas'
    | '/catalogo'
    | '/dashboard'
    | '/campanas/$campaignId'
    | '/catalogo/$productId'
    | '/campanas/'
    | '/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampanasRoute: typeof CampanasRouteWithChildren
  CatalogoRoute: typeof CatalogoRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas/': {
      id: '/campanas/'
      path: '/'
      fullPath: '/campanas/'
      preLoaderRoute: typeof CampanasIndexRouteImport
      parentRoute: typeof CampanasRoute
    }
    '/campanas/$campaignId': {
      id: '/campanas/$campaignId'
      path: '/$campaignId'
      fullPath: '/campanas/$campaignId'
      preLoaderRoute: typeof CampanasCampaignIdRouteImport
      parentRoute: typeof CampanasRoute
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$productId': {
      id: '/catalogo/$productId'
      path: '/$productId'
      fullPath: '/catalogo/$productId'
      preLoaderRoute: typeof CatalogoProductIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CampanasRouteChildren {
  CampanasCampaignIdRoute: typeof CampanasCampaignIdRoute
  CampanasIndexRoute: typeof CampanasIndexRoute
}

const CampanasRouteChildren: CampanasRouteChildren = {
  CampanasCampaignIdRoute: CampanasCampaignIdRoute,
  CampanasIndexRoute: CampanasIndexRoute,
}

const CampanasRouteWithChildren = CampanasRoute._addFileChildren(
  CampanasRouteChildren,
)

interface CatalogoRouteChildren {
  CatalogoProductIdRoute: typeof CatalogoProductIdRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoProductIdRoute: CatalogoProductIdRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampanasRoute: CampanasRouteWithChildren,
  CatalogoRoute: CatalogoRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
